spring:
    datasource:
        driver-class-name: com.ibm.db2.jcc.DB2Driver
        password: rLoa7vFf
        url: jdbc:db2://dsn01d.db.bnsf.com:55000/dsn01d
        username: NPCRMRW
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.DB2Dialect
        show-sql: true
